# coding: utf-8

"""
    LINE Messaging API

    This document describes LINE Messaging API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AudienceGroupJobStatus(str, Enum):
    """
    Job status
    """

    """
    allowed enum values
    """
    QUEUED = 'QUEUED'
    WORKING = 'WORKING'
    FINISHED = 'FINISHED'
    FAILED = 'FAILED'

    @classmethod
    def from_json(cls, json_str: str) -> AudienceGroupJobStatus:
        """Create an instance of AudienceGroupJobStatus from a JSON string"""
        return AudienceGroupJobStatus(json.loads(json_str))


