# coding: utf-8

"""
    LINE Messaging API

    This document describes LINE Messaging API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AudienceGroupAuthorityLevel(str, Enum):
    """
    authority level
    """

    """
    allowed enum values
    """
    PUBLIC = 'PUBLIC'
    PRIVATE = 'PRIVATE'

    @classmethod
    def from_json(cls, json_str: str) -> AudienceGroupAuthorityLevel:
        """Create an instance of AudienceGroupAuthorityLevel from a JSON string"""
        return AudienceGroupAuthorityLevel(json.loads(json_str))


