# coding: utf-8

"""
    LINE Messaging API

    This document describes LINE Messaging API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AreaDemographic(str, Enum):
    """
    AreaDemographic
    """

    """
    allowed enum values
    """
    JP_01 = 'jp_01'
    JP_02 = 'jp_02'
    JP_03 = 'jp_03'
    JP_04 = 'jp_04'
    JP_05 = 'jp_05'
    JP_06 = 'jp_06'
    JP_07 = 'jp_07'
    JP_08 = 'jp_08'
    JP_09 = 'jp_09'
    JP_10 = 'jp_10'
    JP_11 = 'jp_11'
    JP_12 = 'jp_12'
    JP_13 = 'jp_13'
    JP_14 = 'jp_14'
    JP_15 = 'jp_15'
    JP_16 = 'jp_16'
    JP_17 = 'jp_17'
    JP_18 = 'jp_18'
    JP_19 = 'jp_19'
    JP_20 = 'jp_20'
    JP_21 = 'jp_21'
    JP_22 = 'jp_22'
    JP_23 = 'jp_23'
    JP_24 = 'jp_24'
    JP_25 = 'jp_25'
    JP_26 = 'jp_26'
    JP_27 = 'jp_27'
    JP_28 = 'jp_28'
    JP_29 = 'jp_29'
    JP_30 = 'jp_30'
    JP_31 = 'jp_31'
    JP_32 = 'jp_32'
    JP_33 = 'jp_33'
    JP_34 = 'jp_34'
    JP_35 = 'jp_35'
    JP_36 = 'jp_36'
    JP_37 = 'jp_37'
    JP_38 = 'jp_38'
    JP_39 = 'jp_39'
    JP_40 = 'jp_40'
    JP_41 = 'jp_41'
    JP_42 = 'jp_42'
    JP_43 = 'jp_43'
    JP_44 = 'jp_44'
    JP_45 = 'jp_45'
    JP_46 = 'jp_46'
    JP_47 = 'jp_47'
    TW_01 = 'tw_01'
    TW_02 = 'tw_02'
    TW_03 = 'tw_03'
    TW_04 = 'tw_04'
    TW_05 = 'tw_05'
    TW_06 = 'tw_06'
    TW_07 = 'tw_07'
    TW_08 = 'tw_08'
    TW_09 = 'tw_09'
    TW_10 = 'tw_10'
    TW_11 = 'tw_11'
    TW_12 = 'tw_12'
    TW_13 = 'tw_13'
    TW_14 = 'tw_14'
    TW_15 = 'tw_15'
    TW_16 = 'tw_16'
    TW_17 = 'tw_17'
    TW_18 = 'tw_18'
    TW_19 = 'tw_19'
    TW_20 = 'tw_20'
    TW_21 = 'tw_21'
    TW_22 = 'tw_22'
    TH_01 = 'th_01'
    TH_02 = 'th_02'
    TH_03 = 'th_03'
    TH_04 = 'th_04'
    TH_05 = 'th_05'
    TH_06 = 'th_06'
    TH_07 = 'th_07'
    TH_08 = 'th_08'
    ID_01 = 'id_01'
    ID_02 = 'id_02'
    ID_03 = 'id_03'
    ID_04 = 'id_04'
    ID_05 = 'id_05'
    ID_06 = 'id_06'
    ID_07 = 'id_07'
    ID_08 = 'id_08'
    ID_09 = 'id_09'
    ID_10 = 'id_10'
    ID_11 = 'id_11'
    ID_12 = 'id_12'

    @classmethod
    def from_json(cls, json_str: str) -> AreaDemographic:
        """Create an instance of AreaDemographic from a JSON string"""
        return AreaDemographic(json.loads(json_str))


