# coding: utf-8

"""
    LINE Messaging API

    This document describes LINE Messaging API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FlexBoxSpacing(str, Enum):
    """
    You can specify the minimum space between two components with the `spacing` property of the parent box component, in pixels or with a keyword. FlexBoxSpacing just provides only keywords. 
    """

    """
    allowed enum values
    """
    NONE = 'none'
    XS = 'xs'
    SM = 'sm'
    MD = 'md'
    LG = 'lg'
    XL = 'xl'
    XXL = 'xxl'

    @classmethod
    def from_json(cls, json_str: str) -> FlexBoxSpacing:
        """Create an instance of FlexBoxSpacing from a JSON string"""
        return FlexBoxSpacing(json.loads(json_str))


