# coding: utf-8

"""
    LINE Messaging API

    This document describes LINE Messaging API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic.v1 import BaseModel, Field, StrictStr

class MarkMessagesAsReadByTokenRequest(BaseModel):
    """
    MarkMessagesAsReadByTokenRequest
    https://developers.line.biz/en/reference/messaging-api/#mark-as-read-request-body
    """
    mark_as_read_token: StrictStr = Field(..., alias="markAsReadToken", description="Token used to mark messages as read.")

    __properties = ["markAsReadToken"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MarkMessagesAsReadByTokenRequest:
        """Create an instance of MarkMessagesAsReadByTokenRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MarkMessagesAsReadByTokenRequest:
        """Create an instance of MarkMessagesAsReadByTokenRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MarkMessagesAsReadByTokenRequest.parse_obj(obj)

        _obj = MarkMessagesAsReadByTokenRequest.parse_obj({
            "mark_as_read_token": obj.get("markAsReadToken")
        })
        return _obj

