# coding: utf-8

"""
    LINE Messaging API

    This document describes LINE Messaging API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic.v1 import BaseModel, Field, StrictStr, conlist, constr, validator
from linebot.v3.messaging.models.pnp_templated_message_body import PnpTemplatedMessageBody

class PnpTemplatedMessageRequest(BaseModel):
    """
    PnpTemplatedMessageRequest
    https://developers.line.biz/en/reference/line-notification-messages/#send-line-notification-message-template
    """
    to: StrictStr = Field(..., description="Message destination. Specify a phone number that has been normalized to E.164 format and hashed with SHA256.")
    template_key: StrictStr = Field(..., alias="templateKey", description="Specify the key of the template you want to send. For available keys, see https://developers.line.biz/en/docs/partner-docs/line-notification-messages/template/#templates ")
    body: Optional[PnpTemplatedMessageBody] = None
    custom_aggregation_units: Optional[conlist(constr(strict=True, max_length=30, min_length=1), max_items=1)] = Field(None, alias="customAggregationUnits", description="Name of aggregation unit. Case-sensitive. For more information about assigning a unit name, see https://developers.line.biz/en/docs/messaging-api/unit-based-statistics-aggregation/#assign-names-to-units-when-sending-messages ")

    __properties = ["to", "templateKey", "body", "customAggregationUnits"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PnpTemplatedMessageRequest:
        """Create an instance of PnpTemplatedMessageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic.v1 by calling `to_dict()` of body
        if self.body:
            _dict['body'] = self.body.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PnpTemplatedMessageRequest:
        """Create an instance of PnpTemplatedMessageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PnpTemplatedMessageRequest.parse_obj(obj)

        _obj = PnpTemplatedMessageRequest.parse_obj({
            "to": obj.get("to"),
            "template_key": obj.get("templateKey"),
            "body": PnpTemplatedMessageBody.from_dict(obj.get("body")) if obj.get("body") is not None else None,
            "custom_aggregation_units": obj.get("customAggregationUnits")
        })
        return _obj

