[tool.ruff]
# Exclude commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

[tool.ruff.lint]
# Only enable the rule for missing imports.
ignore = []
select = [
  "F821",
]

# Optionally enable fixable support.
# fixable = ["F821"]

[tool.ruff.format]
# Retain formatting configurations similar to Black.
indent-style = "space"
line-ending = "auto"
quote-style = "single"
skip-magic-trailing-comma = false
