# coding: utf-8

"""
    LINE Messaging API(Insight)

    This document describes LINE Messaging API(Insight).  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic.v1 import BaseModel, Field, conlist
from linebot.v3.insight.models.get_rich_menu_insight_daily_response_bounds import GetRichMenuInsightDailyResponseBounds
from linebot.v3.insight.models.get_rich_menu_insight_daily_response_daily_metrics import GetRichMenuInsightDailyResponseDailyMetrics

class GetRichMenuInsightDailyResponseClick(BaseModel):
    """
    Daily click metrics for a single tappable area of the rich menu.
    """
    bounds: GetRichMenuInsightDailyResponseBounds = Field(...)
    metrics: conlist(GetRichMenuInsightDailyResponseDailyMetrics) = Field(..., description="Per-day click metrics for the target area.")

    __properties = ["bounds", "metrics"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRichMenuInsightDailyResponseClick:
        """Create an instance of GetRichMenuInsightDailyResponseClick from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic.v1 by calling `to_dict()` of bounds
        if self.bounds:
            _dict['bounds'] = self.bounds.to_dict()
        # override the default output from pydantic.v1 by calling `to_dict()` of each item in metrics (list)
        _items = []
        if self.metrics:
            for _item in self.metrics:
                if _item:
                    _items.append(_item.to_dict())
            _dict['metrics'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRichMenuInsightDailyResponseClick:
        """Create an instance of GetRichMenuInsightDailyResponseClick from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRichMenuInsightDailyResponseClick.parse_obj(obj)

        _obj = GetRichMenuInsightDailyResponseClick.parse_obj({
            "bounds": GetRichMenuInsightDailyResponseBounds.from_dict(obj.get("bounds")) if obj.get("bounds") is not None else None,
            "metrics": [GetRichMenuInsightDailyResponseDailyMetrics.from_dict(_item) for _item in obj.get("metrics")] if obj.get("metrics") is not None else None
        })
        return _obj

