# coding: utf-8

"""
    LINE Messaging API(Insight)

    This document describes LINE Messaging API(Insight).  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic.v1 import BaseModel, Field, StrictInt, constr, validator

class GetRichMenuInsightDailyResponseDailyMetrics(BaseModel):
    """
    Aggregated number of events and unique users for a single day.
    """
    var_date: constr(strict=True) = Field(..., alias="date", description="The date (JST) of these metrics. Format: yyyyMMdd (e.g. 20260213).")
    count: StrictInt = Field(..., description="Number of impressions or clicks on this day.")
    unique_users: StrictInt = Field(..., alias="uniqueUsers", description="Approximate number of unique users who triggered an impression or click on this day.")

    __properties = ["date", "count", "uniqueUsers"]

    @validator('var_date')
    def var_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9]{8}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{8}$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRichMenuInsightDailyResponseDailyMetrics:
        """Create an instance of GetRichMenuInsightDailyResponseDailyMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRichMenuInsightDailyResponseDailyMetrics:
        """Create an instance of GetRichMenuInsightDailyResponseDailyMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRichMenuInsightDailyResponseDailyMetrics.parse_obj(obj)

        _obj = GetRichMenuInsightDailyResponseDailyMetrics.parse_obj({
            "var_date": obj.get("date"),
            "count": obj.get("count"),
            "unique_users": obj.get("uniqueUsers")
        })
        return _obj

