# coding: utf-8

"""
    LINE Messaging API(Insight)

    This document describes LINE Messaging API(Insight).  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic.v1 import BaseModel, Field
from linebot.v3.insight.models.get_rich_menu_insight_summary_response_bounds import GetRichMenuInsightSummaryResponseBounds
from linebot.v3.insight.models.get_rich_menu_insight_summary_response_metrics import GetRichMenuInsightSummaryResponseMetrics

class GetRichMenuInsightSummaryResponseClick(BaseModel):
    """
    Click metrics for a single tappable area of the rich menu.
    """
    bounds: GetRichMenuInsightSummaryResponseBounds = Field(...)
    metrics: GetRichMenuInsightSummaryResponseMetrics = Field(...)

    __properties = ["bounds", "metrics"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRichMenuInsightSummaryResponseClick:
        """Create an instance of GetRichMenuInsightSummaryResponseClick from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic.v1 by calling `to_dict()` of bounds
        if self.bounds:
            _dict['bounds'] = self.bounds.to_dict()
        # override the default output from pydantic.v1 by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRichMenuInsightSummaryResponseClick:
        """Create an instance of GetRichMenuInsightSummaryResponseClick from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRichMenuInsightSummaryResponseClick.parse_obj(obj)

        _obj = GetRichMenuInsightSummaryResponseClick.parse_obj({
            "bounds": GetRichMenuInsightSummaryResponseBounds.from_dict(obj.get("bounds")) if obj.get("bounds") is not None else None,
            "metrics": GetRichMenuInsightSummaryResponseMetrics.from_dict(obj.get("metrics")) if obj.get("metrics") is not None else None
        })
        return _obj

