name: Generate code and open pull request

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --remote --recursive
      - uses: actions/setup-node@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate code
        run: |
          python generate-code.py
          diff=$(git --no-pager diff --name-only HEAD)
          echo "DIFF_IS_EMPTY=$([[ -z "$diff" ]] && echo 'true' || echo 'false')" >> $GITHUB_ENV
          echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      ## Run if diff exists and pull request, and make CI status failure (but allow renovate bot)
      - if: ${{ github.event_name == 'pull_request' && env.DIFF_IS_EMPTY != 'true' && github.actor != 'renovate[bot]' }}
        run: |
          echo "There are changes in the generated codes. Please run 'generate-code.py' and commit the changes." >&2
          exit 1
      ## Run if diff exists and event is not pull request, and make PR
      - if: ${{ github.event_name != 'pull_request' && env.DIFF_IS_EMPTY != 'true' }}
        run: |
          BRANCH_NAME="update-diff-${{ env.CURRENT_DATETIME }}"

          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $BRANCH_NAME

          git add .
          git commit -m "Code are generated by openapi generator"

          git push origin $BRANCH_NAME

          # Determine PR title and body
          if [ "$CHANGE_TYPE" == "submodule-update" ]; then
            # Fetch PR info from submodule
            npx zx ./line-openapi/tools/get-pr-info.mjs
            PR_INFO=$(cat pr_info.json)
            TITLE=$(echo "$PR_INFO" | jq -r '.title')
            BODY=$(echo "$PR_INFO" | jq -r '.url')$'\n\n'$(echo "$PR_INFO" | jq -r '.body')
          else
            # Default PR title and body
            TITLE="Codes are generated by openapi generator"
            BODY="⚠Reviewer: Please edit this description to include relevant information about the changes.⚠"
          fi

          gh pr create -B ${{ github.ref_name }} -H $BRANCH_NAME -t "$TITLE" -b "$BODY" --label "line-openapi-update"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
